name: my_bible_pencil
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  flutter_staggered_grid_view: ^0.7.0
  path_provider: ^2.1.0
  sqflite: ^2.3.0
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  device_info_plus: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

# 지원 플랫폼 설정
platforms:
  android: true
  ios: true
  web: false
  windows: false
  macos: false
  linux: false 